export const fishFacts = [
  'Most fish reproduce by laying eggs, though some fish, such as great white sharks, give birth to live babies called pups.',
  'Lungfish can live out of water for several years. It secretes a mucus cocoon and burrows itself under the unbaked earth. It takes in air with its lung through a built-in breathing tube that leads to the surface. A lungfish has both gills and a lung.',
  'Some fish, such as the great white shark, can raise their body temperature. This helps them hunt for prey in cold water.',
  'The oldest known age for a fish was an Australian lungfish. In 2003, it was still alive and well at 65 years old.',
  'Starfish are not fish. Neither are jellyfish.',
  'Since a fish\'s jaw is not attached to its skull, many fishes can shoot their mouths forward like a spring to catch startled prey.',
  'Electric eels and electric rays have enough electricity to kill a horse.',
  'Sharks are the only fish that have eyelids.',
  'Fish have sleep-like periods where they have lowered response to stimuli, slowed physical activity, and reduced metabolism but they do not share the same changes in brain waves as humans do when they sleep.',
  'Some fish, such as the herbivorous fish (grazers), often lack jaw teeth but have tooth-like grinding mills in their throats called pharyngeal teeth.',
  'Most fish have taste buds all over their body.',
  'An estimated one third of male fish in British waters are changing sex due to pollution in human sewage.',
  'Saltwater fish need to drink more water than freshwater fish. Since seawater is saltier than the liquids in a fish\'s body, water inside the fish is constantly flowing out. If they didn\'t drink to replace the lost water, saltwater fish would dry up like prunes.',
  'The oldest fishhook ever found dates back to about 42,000 years ago.',
  'Most fish have little salt in them. Sharks, however, have meat as salty as the ocean they live in.',
  'Most brands of lipstick contain fish scales.',
  'A fish does not add new scales as it grows, but the scales it has increase in size. In this way, growth rings are formed and the rings reveal the age of a fish.',
  'Fish that have thin fins with a split tail indicate that they move very quickly or may need them to cover great distances. On the other had, fish that live among rocks and reefs near the ocean floor have broad lateral fin and large tails.',
  'A ship has a heavy keel in the lower part to keep it from capsizing. Fish, on the other hand, have the keel on top. If the paired fins stop functioning to keep the fish balanced, the fish turns over because its heaviest part tends to sink, which happens when it dies.',
  'On average, flying fish can glide 160 feet (50m), but have been known to glide as far as 660 feet (200 m). And they can reach heights up to 19 feet (6m).',
  'A fish can drown in water. Like humans, fish need oxygen, so if there isn\'t enough oxygen in the water, they will suffocate.',
  'Although the fang tooth fish is only a few inches long, it has teeth about the size of a human\'s.',
  'The fish in the middle of a school control the school. The fish on the outside are guided by those in the middle. Only bony fish can swim in highly coordinated groups.',
  'Most fish cannot swim backwards. Those that can are mainly members of one of the eel families.',
  'Fish would suffocate if they tried to chew because chewing would interfere with water passing over their gills.',
  'The biggest fish in the world is the giant whale shark, which can grow to nearly 60 feet, or the length of two school buses. It weighs over 25 tons and eats mainly plankton. It has over 4,000 teeth, though they are only 3 mm long.',
  'The most poisonous fish in the world is the stone fish. Its sting can cause shock, paralysis, and even death if not treated within a few hours.',
  'The word "piranha" is from the Tupi (Brazil) "pira nya" and means "scissors."',
  'Found in freshwater rivers in South America, piranhas have razor-sharp teeth. They typically eat fish, insects, seeds, fruit, and even larger animals such as horses.',
  'While there are no proven reports of piranhas killing a person, they do eat human carcasses.',
  'The fastest fish is the sailfish. It can swim as fast as a car travels on the highway.',
  'Seahorses are the only fish that swim upright.',
  'The slowest fish is a seahorse. It swims so slowly that a person can barely tell it is moving. The slowest is the Dwarf Seahorse, which takes about one hour to travel five feet. It even looks like it is simply standing up, not swimming.',
  'Some fish do not have scales. Sharks, for example, have rough sandpapery skin instead of scales.',
  'Hammerhead sharks can live in schools of more than 500 sharks. The strongest female swims in the middle. When she is ready to mate, she shakes her head from side to side to signal the other female sharks.',
  'Some desert pupfish can live in hot springs that reach temperatures greater than 113° F.',
  'A male emperor angelfish lives together with up to five female mates. If the emperor angelfish dies, one of the females turns into a male fish and becomes the leader of the group.',
  'The mudskipper is a fish that spends most of its time out of water and can "walk" on its fins. It carries a portable water supply in its gill chambers when it leaves the water. It can also breathe through the pores of its wet skin.',
  'There are approximately 32,000 different kinds of fish in the world today, which is more than all the other kinds of vertebrates combined. Scientists are discovering new species all the time.',
  'The batfish plays dead when danger is near. It floats motionless on its side when scared, making it look like a dead leaf floating on the surface of the water.',
  'Anableps, four-eyed fish, can see above and below water at the same time.',
  'Sometimes tornadoes pick up fish while traveling over water and carry them over land, where the fish rain down. These "fish showers" have been happening for thousands of years.',
  'Scientists have explored only 1% of the ocean depths. They believe millions of new kinds of animals and fish are down there, waiting to be discovered.',
  'Empty dogfish egg cases sometimes wash up onto the beach. Some people call them mermaid purses.',
  'The entire body of a catfish is covered with taste buds.',
  'Catfish have over 27,000 taste buds. Humans have around 7,000.',
  'Fish were the first vertebrates with bony skeletons to appear on Earth. Unlike today\'s fish, early fish had no scales, fins, or jawbone, but they did have a dorsal fin.',
  'Hagfish are some of the slimiest animals on earth. An Atlantic hagfish can make enough slime in one minute to fill a bucket.',
  'Unlike bony fish, sharks and rays do not have swim bladders. They have to swim all the time, even when they are sleeping. Otherwise, they will sink to the bottom of the ocean.',
  'A seahorse can move each of its eyes separately. One eye can look forward while the other looks backward. Seahorses can also change their color to match their surroundings.',
  'The term "fish" is used when referring to one species of fish (e.g., 10 salmon are 10 fish).',
  'The term "fishes" is used when referring to more than one species (e.g., 10 salmon, 3 trout, and 1 angel fish are 14 fishes).',
  'Unlike most other fish, the ocean sunfish does not have a tail. A female sunfish can lay 300 million eggs each year. Each egg is smaller than the period at the end of this sentence.',
  'Lampreys and hagfish are the most primitive form of fish still living today.',
  'Mudskippers are able to jump 2 feet in the air.',
  'Seahorses are poor swimmers and can die of exhaustion in stormy waters.',
  'Starifish dont have blood or a brain.',
  'Fish have been on the earth for more than 450 million years.',
  'Fish were well established long before dinosaurs roamed the earth.',
  'There are over 25,000 identified species of fish on the earth.',
  'It is estimated that there may still be over 15,000 fish species that have not yet been identified.',
  'There are more species of fish than all the species of amphibians, reptiles, birds and mammals combined.',
  '40% of all fish species inhabit fresh water, yet less than .01% of the earth\'s water is fresh water.',
  'The spotted climbing perch is able to absorb oxygen from the air and will crawl overland using its strong pectoral fins.',
  'Some fish like sharks don\'t posses an air bladder to help keep them afloat and must either swim continually or rest on the bottom.',
  'Some fish make sounds by grating their teeth and others like some catfish make sounds from their air filled swim bladder.',
  'Some species of fish can fly (glide) others can skip along the surface and others can even climb rock.',
  'Fish have a specialized sense organ called the lateral line which works much like radar and helps them navigate in dark or murky water.',
  'The largest fish is the great whale shark which can reach fifty feet in length.',
  'The smallest fish is the Philippine goby that is less than 1/3 of an inch when fully grown.',
  'Some species of fish have skeletons made only of cartilage.',
  'Fish have excellent senses of sight, touch, taste and many possess a good sense of smell and "hearing".',
  'Fish feel pain and suffer stress just like mammals and birds.',
  'Tropical fish are one of the most popular pets in the U.S.',
  '95% of tropical fish mortality results from improper housing and nutrition.',
  'Many tropical fish sold in the United States are harvested from the wild in Africa, Asia, and Central and South America.',
  'There\'s a species of fish called "Slippery Dick".',
  'Many Fish can taste without even opening their mouths.',
  'Some Fish, like the Triggerfish, can swim backward.',
  'Goldfish can\'t close their eyes as they have no eyelids.',
  'Many fish species are known to change sex during the course of their lives.',
  'Sharks kill 12 people per year while people kill 11,417 sharks per hour.',
  'Goldfish can see infrared radiation that is invisible to us.',
  'There\'s a shark in Greenland that eats polar bears and can live up to 200 years.',
  'One Puffer Fish contains enough poison to kill 30 people.',
  'If you keep a goldfish in a dark room, it will lose its color.',
  '80% of the biomass of fish in the world\'s oceans has been lost in the past 100 years.',
  'Thousands of marine creatures die by mistakenly swallowing plastic bags that resemble jellyfish.',
  'Starfish don\'t have brains. Special cells on their skin gather information about their surroundings.',
  'There is a starfish with 40 arms.',
  'Fish can drown in water.',
  '"Rain of fish" is an annual weather event in which hundreds of fish rain from the sky onto the city Yoro in Honduras.',
  'Starfish can re-grow their arms. In fact, a single arm can regenerate a whole body.',
  'Fish in polluted lakes lose their sense of smell.',
  'Goldfish can distinguish the music of one composer from another.',
  'A 10-Year-Old Goldfish Had a 45-Minute Surgery To Remove A Tumor in 2014.',
  'When Anglerfish mate, they melt into each other and share their bodies forever.',
  'About a third of male fish in British rivers are changing sex due to pollution, especially from contraceptive pills.',
  'A robotic fish was accepted by other fish and became their leader during an experiment by NYU.',
  'The goliath tigerfish is a fish that eats small crocodiles.',
  'A koi fish named "Hanako" lived for 225 years.',
  'The Salema Porgy is a species of fish that can cause hallucinations when eaten. In Ancient Rome it was consumed as a recreational drug.',
  'Fossil evidence suggests that fish have been on Earth for about 530 million years.',
  'The opah, or "moonfish", is the only known fully warm-blooded fish.',
  'Goldfish don\'t have stomachs and should therefore be fed easily digestible food in lots of small feeding sessions.',
  'The toxin in puffer fish is 1200 times deadlier than cyanide.',
  'In three decades, the world\'s oceans will contain more discarded plastic than fish when measured by weight.',
  'Around 10% of the world\'s total fish species can be found just within the Great Barrier Reef.',
  'Over 40,000 plant species, 2,200 fishes, 1,200 birds, 420 mammals, 420 amphibians, and 370 reptiles have been scientifically classified in the Amazon region.',
  'Jellyfish are the ocean\'s most efficient swimmers, consuming 48% less oxygen than any other swimming animal.',
  'In Ohio, it is against state law to get a fish drunk.',
  'A fish discovered in Australia in 2015 was named "Blue Bastard".',
  'Some piranhas are cannibals.',
  'Piranhas only attack you if you mess with them or their eggs.',
  'Fish can see 70 times further in air than in water.',
  'The Climbing gourami is a fish that has the ability to climb out of water, breathe oxygen, and even walk for short distances.',
  'The eyes of the celestial eye goldfish are bigger than its stomach.',
  'Herrings form mega schools that are billions strong.',
  'An electric eel can shock a horse off its feet.',
  'Sunfish can produce 300 million eggs.',
  'Whales have belly buttons.',
  'There’s a jellyfish species that can age backwards.',
  'The oldest koi carp on record reached 226 years.',
  "The Dwarf Seahorse is so slow you can't see it move.",
  "The Humuhumunukunukuapua'a is Hawaii's state fish.",
  'The biggest fish in the world is the giant whale shark which can grow to a length of around 60ft.',
  'Tuna can swim at speeds of up to 70 kph (43 mph).',
  'Some flatfish use camouflage to hide themselves on the ocean floor.',
  'Fish have gills that extract oxygen from the water around them.',
  'Relative to their body size, fish have small brains compared to most other animals.',
  'Fish are covered in scales which are often covered in a layer of slime to help their movement through water.',
  'Cleaner fish help out other fish by removing parasites and dead skin from their scales.',
  'Although jellyfish and crayfish have the word ‘fish’ in their name, they aren’t actually fish.',
  'Over 1000 fish species are threatened by extinction.',
  'American Lobsters have longer life spans than both cats and dogs, living over 20 years.',
  'Fish can get sunburn, but it is unusual.',
  'The Antarctic ice fish, which have antifreeze in their blood, live permanently at -1°C.',
  'Fish have a specialised sense organ called their lateral line, which works much like radar and helps them navigate in dark or murky water.',
  'It was not until 1853 in London, UK, when aeration and filtration of water was understood, that people were able to keep fish as indoor pets.',
  'Reef triggerfish are quite common and can be found in shallow water near reefs in the waters of Hawaii, Polynesia Australia, Micronesia, Melanesia, the Philippines, the coast of Africa, the Red Sea and southern Japan.',
  'Tuna can reach length of 6.5 feet and weight of up to 550 pounds.',
  'Largest (ever recorded) specimen of tuna was 21 feet long, weighing 1600 pounds.',
  'Despite their large size, tunas are very fast swimmers. They can reach the speed between 44 and 62 miles per hour.',
  'Tuna can swim near the surface or can dive to the depth of 3000 feet while it searches for food.',
  'Tuna is a carnivore. It feeds on different types of fish (mackerel, herring, hake…), squids and crustaceans.',
  'Tuna breathes oxygen from the water and because of that it needs to swim constantly.',
  'Average life span of tuna is between 15 and 30 years in the wild. Small percent of tuna managed to survive until this period.',
  'Puffer fish vary in size from one inch long pygmy puffer, to a two feet long freshwater giant puffer.',
  'Scientists believe that puffer fish developed this tactic as a method of the self-defense because they are poor swimmers that cannot escape from the danger quickly.',
  'Sharks are the only species immune to the puffer fish\'s toxin. They can eat puffer fish without any negative consequences.',
  'Puffer fish do not have scales. Their skin is thick and rough. Some species have spines on the skin, which offer additional protection against the predators.',
  'The most elastic part a puffer fish\'s body is skin on the stomach area. When puffer fish ingests water, skin on the stomach expands several times of the normal size of the fish.',
  'Average lifespan of the puffer fish is around 10 years.',
  'Although some baby puffer fish cannot be seen without magnifying glass, their body shape resembles those of the adult animals.',
  'Puffer fish have excellent eyesight.',
  'Starfish vary in size. They usually have five to ten inches in length and weigh up to 11 pounds.',
  'Common feature for all starfish is that their body is radially symmetrical. That means that their body can be divided in five equal pieces (even if they have more than five arms).',
  'A starfish\'s mouth is located on the underside of its body. It\'s anus is located on the upper side of the body.',
  'Starfish move using tube feet, which consists of hundreds projections on the underside of their bodies. They are used for walking and catching of the prey.',
  'Starfish do not have a brain. They also do not have blood like other animals. Instead of blood, sea water circulates through their body with the help of sieve plate.',
  'Surface of the starfish body is covered with bony skeleton which often contains different kind of spikes and thorns. They serve as excellent protection against predators.',
  'Typical predators of the starfish are sea otters, rays, sharks, seagulls and different types of fish.',
  'Starfish can survive up to 35 years in the wild.',
  'Jellyfish is made of gelatinous mass which contains 95 percent of water.',
  'Jellyfish are one of the oldest organisms on the planet. They appeared on the Earth before dinosaurs. Scientists believe that jellyfish exist between 500 and 700 million years.',
  'Even dead jellyfish is able to sting. Jellyfish kill more people than sharks each year.',
  'Jellyfish eat different types of food: phytoplankton (algae floating in the superficial water), copepods, fish eggs, larvae of different species and other jellyfish.',
  'Lifespan of the jellyfish ranges from several hours to several months, depending on the species.',
  'Humpback whales have very large flippers that can reach the length of one third of their body size.',
  'Upper side of the body of flying fish is bluish-grey. Their belly is grayish-silver. Flying fish has forked tail. Lower piece of the tail is longer than upper piece.',
  'Flying fish are shaped like torpedo. Their fins are closed when they swim to ensure faster movement through the water.',
  'Flying fish can travel distances of 1.312 feet without rest. This is important because it ensures quick escape from predators.',
  'The Flying fish eat plankton, bacteria and other tiny marine creatures.',
  'Flying fish live in large groups and their number can exceed million individuals during the mating season. Females deposit large number of eggs near the surface of the water.',
  'Clownfish are also known as "anemonefish" because they live in community with sea anemones.',
  'Clownfish are immune to the venom of anemone because they have a thick layer of mucus on the surface of their body.',
  'Besides dead tentacles and anemone\'s leftovers, clownfish eats various algae and plankton.',
  'The clownfish is territorial animal that will fiercely defend its home (anemone) against other clownfish.',
  'The deep sea hatchetfish is named because of unique shape of the body that looks like a hatchet. "Deep sea" means that this fish prefers life on great depths.',
  'The deep sea hatchetfish is able to jump out of the water. It can catch small insects, such as mosquitoes and flies, during the jumps.',
  'What is known about deep sea hatchetfish reproduction is that they are able to release large amount of small, buoyant eggs.',
  'Koi can reach up to 3 feet in length. Size of the fish depends on the living conditions. Adequate amount of food and oxygen and appropriate temperature are essential for the growth of fish.',
  'People in Japan believe that koi fish symbolizes wealth, prosperity, love, successful career and good fortune. Each variety is associated with one of those values.',
  'Koi fish can recognize the person which feeds them and they can be trained to eat from his/her hand.',
  'The koi fish prefers water temperature that ranges from 15 to 25 degrees of Celsius. It doesn\'t tolerate drastic or rapid changes in temperature.',
  'Although life in community can be dangerous, koi fish enjoy company of other koi fish.',
  'Koi fish can mate with goldfish because they are closely related. However, they produce sterile offspring.',
  'Lionfish are famous by their beautifully colored bodies, covered with red, white, orange, black or brown stripes (it depends on the species). Stripes are arranged in zebra-like pattern.',
  'Large mouth of lionfish allows swallowing of the prey in a single bite.',
  'Lionfish often hunts as an ambush predator (using the factor of surprise).',
  'When the food sources are scarce, lionfish will attack and eat members of its own species.',
  'A lionfish\'s Fertilized eggs hatch after 2 days. Babies, called fry, will swim near the surface of the water until they reach the length of at least 1 inch.',
  'Lionfish can survive from 5 to 15 years in the wild.',
  'Dorsal fin of stonefish is modified into 13 spines. Stonefish erects these spines whenever it is threatened.',
  'Venom produced by stonefish induces severe pain, paralysis and tissue necrosis. Since it may lead to heart failure, quick medical help is essential. Complete recovery requires adequate amount of anti-venom.',
  'The stonefish is a slow swimmer, except when it chases the prey.',
  'The stonefish has several predators, such as big sharks (great white and tiger shark) and rays.',
  'The tripod fish has a bronze colored body. Head, belly and lower part of the backs are covered with grey markings.',
  'Elongated rays are rigid when fish stands on the ocean floor and flexible when fish swims. Researchers believe that fish uses some sort of "water pump" to regulate rigidity of rays.',
  'The tripod fish is a carnivore (meat-eater). Its diet includes small crustaceans, shrimps, fish and zooplankton.',
  'The tripod fish is solitary animal. This life style is a result of a life in harsh environment.',
  'Tripod fish are hermaphrodites (one fish possesses both type of reproductive organs). They are able to self-reproduce when they cannot find mating partner.',
  'Most species of catfish have smooth skin (without scales) covered with mucus. Some species of catfish are able to breathe through their skin.',
  'Some species of catfish produce poison in the glands in the skin that covers dorsal fin. In the case of danger, catfish will release toxin that can induce serious (even fatal) injuries in humans.',
  'Main predators of catfish are large fish, birds, reptiles, mammals and humans.',
  'Mating season of most catfish species takes place in the late spring and early summer.',
  'The Name "spiny" refers to the large number of spines that cover the body of spiny crayfish. Spines are often brightly colored and especially numerous on the tail and claws.',
  'The Spiny crayfish has 8 pairs of legs that are used for walking, swimming and for carrying of the eggs (females).',
  'Spiny crayfish live in the burrows on the edges of the streams.',
  'Spiny crayfish are an important source of food for the frogs, fish and platypuses.',
  'Spiny crayfish reach sexual maturity late in life, usually at the age of 6 to 9 years and reproduce slowly (females breed once per year).',
  'Yellow-headed jawfish have a bright yellow head and a bluish green body. Certain populations of yellow-headed jawfish have black spots on the chin.',
  'The yellow-headed jawfish is also known as pearly jawfish due to pearlescent bluish body.',
  'Natural enemies of yellow-headed jawfish are moray eels, frogfish, scorpion fish and triggerfish.',
  'Frogfish dont have scales. Unusual shape of the body and spines (or bumps) on the surface create impression of the sponge.',
  'Frogfish are ambush predators who hunt the prey using the element of surprise. Once the prey is close enough, frogfish swallow it in a blink of an eye (attack lasts 6 milliseconds).',
  'The frogfish rarely swims. It usually walks on the sea floor using the modified pectoral fins.',
  'Natural enemies of frogfish are large species of frogfish and moray eel.',
  'The frogfish can inflate the body to startle the predators.',
  'The monkfish has huge, broad head and gradually tapering tail. Its wide mouth is filled with large number of curved, backward oriented teeth. Eyes resemble the pearls, while pectoral fins look like wings.',
  'The monkfish is also known as "allmouth" due to oversized mouth (compared to the rest of the body).',
  'The monkfish occasionally swims toward the surface of the water to hunt birds such as puffins, grebes, cormorants, gulls and loons.',
  'Each spotted handfish has unique pattern of spots on the body (like fingerprints in humans).',
  'Spotted handfish has pear-shaped body with crest on the back made of skin that stretches between the second and third dorsal spine.',
  'The weakfish has large, slender body with square-shaped tail. It has two large canine teeth in the upper jaw.',
  'The weakfish is a carnivore (meat-eater). Its diet is based on herring, menhaden, killifishes, shrimp, squid, worms and clams.',
  'Schools of weakfish migrate away from the shore, toward the southern, more warmer waters (wintering grounds) during the autumn.',
  'Weakfish return to the same estuaries each year to reproduce.',
  'Scientific name of lake whitefish is Coregonus clupeaformis. It shares many morphological similarities with herring, hence the name clupeaformis ("herring-shape" in Latin).',
  'The lake whitefish resides in deep waters during the summer and winter. It migrates toward the shallow waters at the beginning of the spring and fall.',
  'Young lake whitefish eat zooplankton until they reach length of 3 to 4 inches and become large enough to hunt bigger prey.',
  'The lumpfish uses sucking disks to attach itself to rocks or other objects.',
  'The lumpfish is poor swimmer. Its small, but heavy body is not designed for fast swimming.',
  'Both freshwater and marine angelfish have thin, laterally-compressed body, small mouth and long dorsal and anal fins.',
  'Young freshwater angelfish often live in the group, while adults prefer solitary life. They become territorial and aggressive toward other fish when they reach adulthood.',
  'Angelfish are not agile swimmers and they cannot cope with strong currents in the water.',
  'The cuttlebone is the only bony structure in the body of cuttlefish. It is oval-shaped and used for regulation of buoyancy. Cuttlebone represents excellent source of calcium for birds.',
  'The cuttlefish has W-shaped pupils and ability to see polarized light (unlike humans).',
  'Sense of taste of cuttlefish is located on the suckers.',
  'The dusky dolphin can reach 5 to 7 feet in length and 176 to 264 pounds of weight.',
  'The dusky dolphin has 24 to 36 pairs of cone-shaped, sharp teeth, designed to firmly hold slippery prey.',
  'Unusual morphology of head and jelly-like texture of body are the reasons why blobfish was marked as the ugliest creature on the planet in 2013.',
  'The blobfish does not have a swim bladder like other fish because it would collapse in the atmosphere of huge pressure and result in bursting of the body.',
  'The only natural enemies of blobfish are humans.',
  'The blobfish doesn\'t have commercial value (its jelly-like flesh is not tasty).',
  'Blobfish cannot be kept as a house pet, because aquariums cannot mimic extreme conditions, such as huge pressure, that are typical for the natural environment of this fish.',
  'Blobfish is not endangered species.',
  'Blobfish is not aggressive and it will not attack humans.',
  'The blobfish eats small crustaceans that live on the ocean floor.',
  'Blobfish is not a good swimmer. It floats above the sea floor and waits for the prey to appear in the vicinity.',
  'The blobfish is a bottom dweller that can be found on the depths between 2.000 and 4.000 feet.',
  'Blobfish can reach 12 inches in length and weigh up to 20 pounds.',
]