name: Build

on:
  push:
    branches:
      - 'main'
      - 'discord-go-rewrite'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master

      - name: Build
        run: |
          docker build -t konstfish/fishbot:latest .