# Publish docker containers to github registry
name: Publish

on:
  # Trigger the workflow on a new release github.event.release.tag_name
  release:
    types:
      - created 
  #push:
  #  branches:
  #    - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build fishbot
        uses: docker/build-push-action@v2
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/konstfish/fishbot:${{ github.event.release.tag_name }}
            ghcr.io/konstfish/fishbot:latest